### ISSUE TITLE
Strict parameter types cause rspec tests to fail

### ISSUE THREAD

**Issue by blackknight36** [jflorian/doubledog-systemd#2]
Recent changes to this module are causing rspec unit tests to fail.  When running the rake spec task there are several errors shown similar to this.

> Expected parameter 'ensure' of 'Systemd::Unit[umask.conf]' to have type Systemd::File::Ensure, got String

Changing the class parameters to allow a String value along with the Systemd::File::Ensure corrects this.  For example:

```
define systemd::unit (
        Variant[String, Systemd::File::Ensure]  $ensure='present',
        Optional[Boolean]                       $enable=true,
        Optional[String]                        $content=undef,
        Optional[String]                        $source=undef,
        Optional[Systemd::Eventlist]            $restart_events=undef,
        Optional[String[1]]                     $path=undef,
        Optional[String[1]]                     $extends=undef,
    ) {
```

For example.

**Comment by jflorian** [comment]
What String value is the rspec trying to use?  Either `'present'` or `'absent'` should work just fine.

**Comment by blackknight36** [comment]
The resource in this case is using the default value since there is no ensure parameter set.

```
systemd::unit{ 'umask.conf':
        source  => 'puppet:///modules/dart/est_servers/umask.conf',
        extends => 'tomcat.service',
 }
```

The rspec code for this resource is as follows.

```
it do
    is_expected.to contain_systemd__unit("umask.conf")
        .with({
          "source" => "puppet:///modules/dart/est_servers/umask.conf",
          "extends" => "tomcat.service",
        })
  end
```
After looking at this a bit more it looks like the issue may be with rspec-puppet not passing types correctly.
